sampler/stories/default/IconItem.js, sampler/stories/default/LabeledItem.js
=> add IconItem

console/src/components/Dialer/Dialer.js, console/src/views/Phone.js
* Updates Dialer to support a callback when a digit is pressed
* Wires up new Input component, clear button, and dialer to Changeable to manage state
=> Add interactivity to phone app

sampler/stories/default/Picker.js
Enact-DCO-1.0-Signed-off-by: Derek Tor <derek.tor@lge.com>
=> Adding Picker

console/src/App/App.js
Enact-DCO-1.0-Signed-off-by: Derek Tor <derek.tor@lge.com>
=> Added DateTimePicker

sampler/stories/default/SliderButton.js, sampler/stories/default/SwitchItem.js
Update Icon dependency to Agate and clean up SwitchItem
=> update sampler dependencies and cleanup

console/src/views/HVAC.js, sampler/stories/default/ToggleButton.js
Update sampler for `ToggleButton`
Agate PR: https://github.com/enactjs/agate/pull/51
https://github.com/enactjs/agate/issues/25
=> ToggleButton: underline update

sampler/stories/default/IconItem.js, sampler/stories/default/SwitchItem.js
Fixes https://github.com/enactjs/agate/issues/33
=> Fix some sampler console errors

sampler/stories/default/ColorPicker.js
Add `ColorPicker` to Storybook
=> Sampler: Add ColorPicker

console/config.sample.js, console/package.json, console/src/App/App.js, console/src/App/AppContextProvider.js, console/src/components/CompactMap/CompactMap.js, console/src/components/MapCore/MapCore.js, console/src/components/MapCore/MapCore.less, console/src/data/ServiceLayer.js, console/src/data/connector.js, console/src/data/conversion.js, console/src/views/Home.js
A substantial update to the map, the addition of a `ServiceLayer` and data services. These integrate with ROSLib and our application state, setting things like the current location, destinations, ETA, bearing and speed.
It includes a major breaking change to the coordinates format used in the MapCore which switches from confusing, easily mistakable arrays, to a lat-lon object with named keys.
The connection established in the ServiceLayer is tracked and has a fallback to the browser's location, though this is an out-of-scope edgecase we support, which could be improved.
The ServiceLayer has the ability to issue appstate changes and act on callbacks it sends out. The idea is that it is the definitive source of all things it provides to the app.
This will need to be tested with access to a …
=> ServiceLayer

console/src/views/DisplaySettings.js, sampler/stories/default/ColorPicker.js
When https://github.com/enactjs/agate/pull/72 is merged, this is the sampler update for `ColorPicker`
=> Sampler: ColorPicker update

console/src/views/DisplaySettings.js
Added 4 more preset colors to the color picker.
=> Console: Add Colors to ColorPicker Settings

console/src/App/App.js, console/src/components/MapCore/MapCore.js, console/src/components/MapCore/MapCore.less, console/src/views/Home.js, console/src/views/Home.less
Included interaction restrictions for attribution in MapBox
=> Support multiple home screen layouts

console/src/components/CompactMap/CompactMap.js, console/src/components/CompactMap/CompactMap.less, console/src/components/MapCore/MapCore.js, console/src/components/MapCore/MapCore.less
We'll need to look into why the map doesn't always update to the current skin style colors. I think this has to do with the`componentDidUpdate` switch. Not sure though.
=> Moved map toolbox to MapCore, added `tools` slot

console/src/components/MapCore/MapCore.js, console/src/views/Dashboard.js
Removed the odometer (commented out) which we can add back in if we get some real data from the simulator to populate it with.
Fixed a warning in MapCore from an unused variable.
=> Dashboard now reports current speed (from the sim)

console/src/App/AppContextProvider.js, console/src/App/userPresetsForDemo.json, console/src/components/UserSelectionPopup/UserSelectionPopup.js, console/src/components/WelcomePopup/WelcomePopup.js
And corrected a typo, look at that!
Enact-DCO-1.0-Signed-off-by: Blake Stephens <blake.stephens@lge.com>
=> Added some initial user configurations for the demo

console/src/components/IconButton/IconButton.js, console/src/components/IconButton/IconButton.less, console/src/components/IconButton/package.json
behaves like a regular button with icon but adds `smallest` prop and styling
=> add app component IconButton

console/src/App/App.js, console/src/components/CompactMusic/CompactMusic.js, console/src/components/WeatherItem/WeatherItem.js, console/src/components/WelcomePopup/WelcomePopup.js, console/src/components/WelcomePopup/WelcomePopup.less, console/src/views/Multimedia.js
* Props properly spread on WelcomePopup's GridListImageItem
* Simpler WelcomePopup image selection
* Removed custom `css` object in leu of just having the classNames match up
=> ENYO-5737: Fixed problems with props, resolved several bugs because of it.

console/src/App/App.js, console/src/components/CallPopup/CallPopup.less, console/src/components/CompactAppList/CompactAppList.js, console/src/components/WeatherItem/WeatherItem.js, console/src/components/WelcomePopup/WelcomePopup.js, console/src/components/WelcomePopup/WelcomePopup.less, console/src/views/DisplaySettings.js, console/src/views/WeatherPanel.js
And thus becomes `space-around`
Also, corrected some Layout and positioning parts of WelcomePopup.
=> PLAT-70504: Chrome 53 doesn't have support for `space-evenly`

console/src/components/UserSelectionPopup/UserSelectionPopup.js, console/src/components/WelcomePopup/WelcomePopup.js, console/src/components/WelcomePopup/WelcomePopup.less, console/src/views/Multimedia.less
Updates to welcome user screen and setting up the elements so it'll be ready to be fully themed according to design
PLAT-69380
=> Update Welcome User Screen

communication-server/src/app.js, components/Communicator.js, copilot/src/App/App.js
...With the ability to bring it back, since it's just commented out.
=> Ad related messaging has been disabled, logging for debugging added

console/src/App/App.js, console/src/App/AppContextProvider.js, console/src/components/Clock/Clock.js, console/src/components/ProfileDrawer/ProfileDrawer.js, console/src/components/ProfileDrawer/ProfileDrawer.less, console/src/components/ProfileDrawer/package.json, console/src/components/UserAvatar/UserAvatar.js, console/src/components/UserAvatar/UserAvatar.less, console/src/components/UserAvatar/package.json, console/src/components/WelcomePopup/WelcomePopup.js, console/src/components/WelcomePopup/WelcomePopup.less, console/src/views/Home.js
Also fixes an AM/PM bug in the clock.
=> PLAT-71221: Implements the ProfileDrawer, compartmentalizes UserAvatar

console/src/components/WelcomePopup/WelcomePopup.js, console/src/components/Widget/Widget.js
Remove expand buttons from welcome widgets
PLAT-71227
=> PLAT-71227: Remove expand buttons from welcome widgets

console/src/components/UserSelectionPopup/UserSelectionPopup.js
Uses `RadioItem`s for user selection popup.
Requires https://github.com/enactjs/agate/pull/87
=> PLAT-71035: User selection screen inside home screen: replace on/off toggles with something more intuitive

console/src/components/MapCore/MapCore.js, console/src/data/ServiceLayer.js
This localizes the route redrawing code inside of MapCore, with a configurable check-interval queue.
Also included is a location fabrication simulator for testing in case the simulator is unavailable.
=> Refactor redrawing

console/src/App/userPresetsForDemo.json, console/src/views/ThemeSettings.js
=> PLAT-71625: Increase brightness of copper theme accent color

console/src/App/userPresetsForDemo.json, console/src/components/CompactScreenMonitor/CompactScreenMonitor.js, console/src/views/Home.js
=> PLAT-71615: Update Laura homescreen to have now playing

console/src/App/App.js, console/src/views/Settings.js, console/src/views/ThemeSettings.js
PLAT-71635.  I took a naive approach and just used state.  I suppose I could have figured out how to use the context adapter to retrieve and store the info but this seemed faster.
=> Allow back from theme selection to previous screen

console/src/components/ContactThumbnail/ContactThumbnail.js, console/src/components/ContactThumbnail/ContactThumbnail.less, console/src/views/Phone.js, console/src/views/Phone.less
=> PLAT-71869: Fix phone contact text display

console/src/data/youtubeapi.json, console/src/views/Multimedia.js
=> Change the order of videos to hide misleading thumbnail

console/src/components/UserSelectionPopup/UserSelectionPopup.js, console/src/components/UserSelectionPopup/UserSelectionPopup.less
Updates for User Selection Screen
- Added avatars to the radio item
- Bigger tap area for radio item
- Bigger buttons 
- Wider popup
=> PLAT-71636: Clean up the user selection screen

console/src/views/Radio.js
Now tunes to 200 KHz increments
Has valid starting value
Has proper US range
Removes invalid preset setting
Allows tuning to max/min value
Tunes properly in vertical and horizontal
=> Fixes a number of bugs in radio tuning

console/src/components/CompactHVAC/CompactHVAC.js, console/src/components/CompactHVAC/CompactHVAC.less
=> PLAT-71805: Set min-width to HVAC button text

console/src/App/userPresetsForDemo.json
Also fixed the indenting on the locations (bonus)
The modified locations were tested on the simulator and account for Mapbox/simulator differences and the lane the car will be in at the destination.
=> PLAT-71437: Updated destinations to work well with the simulator

console/src/views/Multimedia.less
Keep the video list and the video player separated a little bit.
=> PLAT-72117: Full screen multimedia app: add padding between the video list and player

components/ScreenSelectionPopup/ScreenSelectionPopup.js, console/src/App/App.js, copilot/src/App/App.js
Restrict video playback to front screen and one rear screen.
=> PLAT-72118: Select Screen:  Rename screen names and add vertical padding if needed

console/src/components/WeatherItem/WeatherItem.js, console/src/components/WeatherItem/WeatherItem.less, console/src/styles/console-variables.less, console/src/views/WeatherPanel.js
Added unit (°F) to degree label and centered 3-hour weather list.
We should be able to get n-day forecast via other API (https://openweathermap.org/forecast16) but it's throwing an invalid key error for some reason. 
(Try `https://api.openweathermap.org/data/2.5/forecast/daily?lat=37.790966&lon=-122.399219&appid=<your key value here>`)
=> PLAT-72114: Update WeatherItem and WeatherPanel visuals

sampler/stories/default/Spinner.js
Add Spinner sample for
https://github.com/enactjs/agate/pull/112
=> PLAT-84314: Add Spinner Sample

sampler/src/AgateEnvironment/AgateEnvironment.js
Now you can choose the latest skin in Sampler.
=> PLAT-84903: Added Gallium (default) skin to the Agate sampler

sampler/stories/default/Header.js
Add Header sample 
https://github.com/enactjs/agate/pull/116
=> PLAT-84544: Add Header sample

components/Communicator.js, console/src/App/AppContextProvider.js, console/src/components/MapCore/MapCore.js, console/src/components/UserSelectionPopup/UserSelectionPopup.js, console/src/data/ServiceLayer.js, console/src/views/Multimedia.js, console/src/views/Phone.js
Issue Resolved (Resolution)
- Fix input component issue (enter a disabled prop to input component)
- Fix config file (remove a get API key function)
- Fix to play local file or streaming address instead of youtube
- Fixed mcvp to be sent when changing user in userSelectionPopup
- Fixed to display the video played in Iframe in full screen
Feature Added (Resolution)
N/A
This PR is targeting 'IAA2019' branch. Only PR that needs to be merged for demonstration.
PLAT-84912
Enact-DCO-1.0-Signed-off-by: Baekwoo Jung (baekwoo.jung@lge.com)
=> PLAT-84912: Fix input component issue and config file for Console app (phase 3)

sampler/stories/default/Heading.js
Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>
=> PLAT-84726: Add Heading sample

sampler/stories/default/IconItem.js, sampler/stories/default/Item.js, sampler/stories/default/ItemKitchenSink.js, sampler/stories/default/LabeledItem.js
Update `IconItem`, `Item`, and `LabeledItem` samples with updated props.
=> PLAT-84631: Item samples

sampler/stories/default/IconButton.js
=> PLAT-85961: add size huge to IconButton

sampler/stories/default/Button.js, sampler/stories/default/IconButton.js, sampler/stories/default/ToggleButton.js
Add `backgroundOpacity` knob to `Button`
=> PLAT-87183: Add transparent background to Button

sampler/stories/default/Button.js
Add new size to the button component: 
- smallest 
- huge
=> PLAT-88683 Iconbutton needs to be reconciled with Button with Icon component

sampler/stories/default/IconButton.js, sampler/stories/default/Spinner.js
Add spinner knob to `IconButton`
=> PLAT-85965: Add spinner knob

sampler/stories/default/Button.js
Update button component to show animation related props.
=> PLAT-88684 Button needs to be able to animate its separate pieces

sampler/stories/default/Button.js
Add `badge` and `badgeColor` knobs for Button
=> PLAT-85942: Add Button badge knobs

console/src/App/AppContextProvider.js, console/src/components/MapCore/MapCore.js
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek (sc.baek@lge.com)
=> Fixed to retry to get info of weather and map

console/src/App/App.js, console/src/App/AppContextProvider.js, console/src/views/WeatherPanel.js
Updated scenarios for CES 2020
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek (sc.baek@lge.com)
=> Update console app for CES 2020

sampler/stories/default/CheckboxItem.js
Add `CheckboxItem` sample for https://github.com/enactjs/agate/pull/187
=> PLAT-96102: Add CheckboxItem sample

console/src/App/App.js, copilot/src/App/App.js, kitchen-sink/src/App/App.js
Updating apps to use `ThemeDecorator`
=> PLAT-104269: Rename AgateDecorator to ThemeDecorator
